# Falco Exporter Configuration
# This configuration enables Prometheus metrics collection from Falco

# gRPC endpoint configuration
grpc:
  endpoint: "falco:5060"
  timeout: 10s
  retry_count: 3

# Metrics configuration
metrics:
  enabled: true
  port: 9376
  path: "/metrics"
  
  # Custom metrics labels
  labels:
    - "container_name"
    - "container_id"
    - "image"
    - "rule"
    - "priority"

# Logging configuration
logging:
  level: "info"
  format: "json"

# Health check configuration
health:
  enabled: true
  port: 9377
  path: "/health"

# Output configuration
output:
  # Enable stdout output for debugging
  stdout: true
  
  # File output for persistent logging
  file:
    enabled: true
    path: "/var/log/falco-exporter/metrics.log"
    max_size: 100  # MB
    max_backups: 3
    max_age: 28    # days
